/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/accounts/[username]': RouteRecordInfo<'/accounts/[username]', '/accounts/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/fanfics/': RouteRecordInfo<'/fanfics/', '/fanfics', Record<never, never>, Record<never, never>>,
    '/fanfics/[slug]': RouteRecordInfo<'/fanfics/[slug]', '/fanfics/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/fanfics/components/FanficGridCard': RouteRecordInfo<'/fanfics/components/FanficGridCard', '/fanfics/components/FanficGridCard', Record<never, never>, Record<never, never>>,
    '/fanfics/components/FanficListCard': RouteRecordInfo<'/fanfics/components/FanficListCard', '/fanfics/components/FanficListCard', Record<never, never>, Record<never, never>>,
    '/fanfics/create/': RouteRecordInfo<'/fanfics/create/', '/fanfics/create', Record<never, never>, Record<never, never>>,
    '/fanfics/manage/': RouteRecordInfo<'/fanfics/manage/', '/fanfics/manage', Record<never, never>, Record<never, never>>,
    '/fanfics/update/[slug]': RouteRecordInfo<'/fanfics/update/[slug]', '/fanfics/update/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/forum/': RouteRecordInfo<'/forum/', '/forum', Record<never, never>, Record<never, never>>,
    '/help/': RouteRecordInfo<'/help/', '/help', Record<never, never>, Record<never, never>>,
    '/help/faq/': RouteRecordInfo<'/help/faq/', '/help/faq', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/[slug]': RouteRecordInfo<'/posts/[slug]', '/posts/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/users/[username]': RouteRecordInfo<'/users/[username]', '/users/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
  }
}
