
    // this file is automatically generated by version.ts script
    /* tslint:disable */
    export const VERSION = {
  "dirty": true,
  "raw": "v1.0.0-14-ga7318ba-dirty",
  "hash": "ga7318ba",
  "distance": 14,
  "tag": "v1.0.0",
  "semver": {
    "options": {
      "loose": false,
      "includePrerelease": false
    },
    "loose": false,
    "raw": "v1.0.0",
    "major": 1,
    "minor": 0,
    "patch": 0,
    "prerelease": [],
    "build": [],
    "version": "1.0.0"
  },
  "suffix": "14-ga7318ba-dirty",
  "semverString": "1.0.0+14.ga7318ba"
};
    /* tslint:enable */
